name: Deploy to Server

on:
  push:
    paths:
      - 'cloudlab/**'   # 仅当 cloudlab 目录下的文件发生变化时触发
  workflow_dispatch:   # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # v3 版本应该兼容 Node.js 20

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Identify changed directory
      id: changes
      run: |
        CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep "^cloudlab/" | cut -d '/' -f 2 | sort | uniq)
        echo "Changed directories: $CHANGED_DIRS"
        echo "dirs=$CHANGED_DIRS" >> $GITHUB_ENV

    - name: Sync directory to server and restart service
      if: contains(env.dirs, 'homepage')
      run: |
        echo "Syncing homepage directory to server"
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./cloudlab/homepage/ ${{ secrets.USER }}@${{ secrets.H_SERVER_IP }}:~/cloudlab/homepage/
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.H_SERVER_IP }} "cd ~/cloudlab/homepage && docker compose down && docker compose up -d"
